name: Label & comment issues
on:
  issues:
    types:
      - reopened
      - opened
      - closed
  pull_request:
    types:
      - opened
jobs:
  labelAndCommentIssues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach labels to issues
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.
      - name: Comment on closed issue
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue has been resolved. Thank you for your contribution!
  congratulateOnFirstPullRequest:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.number == 1
    steps:
      - name: Congratulate on first pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Congratulations on opening your first pull request! 🎉
